# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b530e20a078632f3221957d778addd926d39af52695ce2f26279da04dd4b45ba84dbc5362ec1b8651e84547a78ebea1c9be96a6302b00b8f5a1ca9f3e5089636

test:
  secret_key_base: ecb1e174684a6a223dcdad191c4448fc9749d432b5ae5be2bce34b5dd08df28d91d7083a0430b3ddde7604a4696cacd20088a1fe2b2a4d5abc6a5fae5acbe57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
